export const OPEN_INVOICE_DRAWER = "OPEN_INVOICE_DRAWER";
export const CLOSE_INVOICE_DRAWER = "CLOSE_INVOICE_DRAWER";
export const SET_SORT_CONFIG = "SET_SORT_CONFIG";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
export const SET_LOADING = "SET_LOADING";
