export const SET_SELECTED_PROJECT = "SET_SELECTED_PROJECT";
export const SET_DATE_RANGE = "SET_DATE_RANGE";
export const SET_SELECTED_STATUS = "SET_SELECTED_STATUS";
export const SET_SEARCH_TEXT = "SET_SEARCH_TEXT";
